// vite-project/components/Create.tsx
import React from 'react';
import "../assets/styles/create.css";
import "../assets/styles/global.css";

function Create(){
  return(
    <div>
        <div className="create">
            <div className="create-container">
                <div className = "create_your_own">
                    <div className="layout-section">
                        <div className="start-creating-container">
                            <button className="btn btn-pink"> Button </button>
                        </div>
                    </div>
                </div>   
            </div>
        </div>
   </div>

    )
}

export default Create;

// client/components/Create.vue
<template>
   <div class="create">
    <div class="create-container">
        <div class = "create_your_own">
            <div class="layout-section">
                <!-- inside white component -->
                <div class="start-creating-container">
                    <button class="btn btn-pink"> Button </button>

    
                </div>
            </div>


        </div>
        
    </div>
   </div>
    
</template>

<script>
export default {
    name: 'AppHeader'
};

</script>


<style lang="css" scoped> 
@import "../assets/styles/create.css";
@import "../assets/styles/global.css";

</style>
