// vite-project/pages/create.tsx
import "../assets/styles/global.css";
import React from "react";
import Navbar from "../components/Navbar";
import Create from "../components/Create";
import Footer from "../components/Footer";

function create() {
  return (
    <div>
    <div>
    <Navbar />
    <Create />
    <Footer />
    
    </div>
  
  </div>

  
  )
}

export default create;

// client/components/Create.vue
<template>
    <div class="Create Container">
        <div class = "create_your_own">
         
            <Card />
            <Card />
      
   

        </div>
        
    </div>
    
</template>

<script>
export default {
    name: 'AppHeader'
};

</script>

<style scoped src="@/assets/styles/create.css"> </style>
