// vite-project/components/Hero.tsx
import "../assets/styles/hero.css";
import "../assets/styles/global.css";
import React from "react";

function Hero() {
    return (
        <div>
    <div className="hero">
        <div className="hero-container">
            <img src="../assets/images/introgamibg.png" className="intro-bg" />
            <div className="hero-title">
                <h1>Introgami</h1>
            </div>
            <div className="hero-description">
                <h2>Letters and Origamis for Introverts </h2>
            </div>

        </div>

    </div>

</div>
    )
}


export default Hero;

// client/components/Hero.vue
<template>
    <div class="hero">
        <div class="hero-container">
            <img src="../assets/images/introgamibg.png" class="intro-bg" />
            <div class="hero-title">
                <h1>Introgami</h1>
            </div>
            <div class="hero-description">
                <h2>Letters and Origamis for Introverts </h2>
            </div>

        </div>

    </div>

</template>


<style lang="css" scoped>
@import "@/assets/styles/hero.css";
 @import "@/assets/styles/global.css";
</style>
