// vite-project/components/QnA.tsx
import React from 'react';
import "../assets/styles/qna.css";
import "../assets/styles/global.css";

function QnA () {
    return (
        <div>
            <div className ="qna">
              <div className="qna-container">
          
          <div className = "qna_bg">
              <div className="cardboard_container">
                  
                  <div className="accordion">
                      <div className="accordion-item">
                          <div className="accordion-item-header">
                              What is Introgami?
                          </div>
                          <div className="accordion-item-body">
                              <div className="accordion-item-body-content">
                                  Introgami is an origami . feaieal
                              </div>
                          </div>
          
                      </div>
                  </div>
          
                      
                  <div className="accordion">
                      <div className="accordion-item">
                          <div className="accordion-item-header">
                              What is xxx?
                          </div>
                          <div className="accordion-item-body">
                              <div className="accordion-item-body-content">
                                  Introgami is an origami . feaieal
                              </div>
                          </div>
          
                      </div>
                  </div>
                      
                  <div className="accordion">
                      <div className="accordion-item">
                          <div className="accordion-item-header">
                              What is zzz?
                          </div>
                          <div className="accordion-item-body">
                              <div className="accordion-item-body-content">
                                  Introgami is an origami . feaieal
                              </div>
                          </div>
          
                      </div>
                  </div>
                      
                  <div className="accordion">
                      <div className="accordion-item">
                          <div className="accordion-item-header">
                              What is yyy?
                          </div>
                          <div className="accordion-item-body">
                              <div className="accordion-item-body-content">
                                  Introgami is an origami . feaieal
                              </div>
                          </div>
          
                      </div>
                  </div>
          
              </div>
          </div>
          </div>
            </div>
              
          </div>
    )
}


export default QnA;

// client/components/QnA.vue
<template>
  <div class ="qna">
    <div class="qna-container">

<div class = "qna_bg">
    <div class="cardboard_container">
        
        <div class="accordion">
            <div class="accordion-item">
                <div class="accordion-item-header">
                    What is Introgami?
                </div>
                <div class="accordion-item-body">
                    <div class="accordion-item-body-content">
                        Introgami is an origami . feaieal
                    </div>
                </div>

            </div>
        </div>

            
        <div class="accordion">
            <div class="accordion-item">
                <div class="accordion-item-header">
                    What is xxx?
                </div>
                <div class="accordion-item-body">
                    <div class="accordion-item-body-content">
                        Introgami is an origami . feaieal
                    </div>
                </div>

            </div>
        </div>
            
        <div class="accordion">
            <div class="accordion-item">
                <div class="accordion-item-header">
                    What is zzz?
                </div>
                <div class="accordion-item-body">
                    <div class="accordion-item-body-content">
                        Introgami is an origami . feaieal
                    </div>
                </div>

            </div>
        </div>
            
        <div class="accordion">
            <div class="accordion-item">
                <div class="accordion-item-header">
                    What is yyy?
                </div>
                <div class="accordion-item-body">
                    <div class="accordion-item-body-content">
                        Introgami is an origami . feaieal
                    </div>
                </div>

            </div>
        </div>

    </div>
</div>
</div>
  </div>
    
</template>


<script>

export default {
    
    mounted() {
    }
}
</script>


<style lang="css" scoped> 
@import "@/assets/styles/qna.css";
@import "@/assets/styles/global.css";

</style>
